Products:
    type: entity
    table: products
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 100
            fixed: true
    lifecycleCallbacks: {  }
